---
# tasks for added docker repo
- name: Import gpg key
  apt_key:
    url: "{{ docker_gpg_url }}"

- name: Import repo
  apt_repository:
    repo: "deb [arch=amd64] {{ docker_url }} {{ ansible_distribution_release | lower }} {{ docker_release_channel }}"
    filename: docker